name: Publish Plugin

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set publish credentials
        run: |
          echo "gradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }}" >> gradle.properties
          echo "gradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }}" >> gradle.properties
      - name: publish to portal
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: --no-daemon -i build publishPlugins -Pgradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }} -Pgradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }}